INSERT INTO address(id, street, city, state, zip) VALUES(null, 'Al.Szucha Jana Chrystiana 1038', 'Warszawa', 'Polska', '00-582');
INSERT INTO address(id, street, city, state, zip) VALUES(null, 'ul.Bracka 84', 'Tarnowskie Góry', 'Polska', '42-605');
INSERT INTO address(id, street, city, state, zip) VALUES(null, 'ul.Ratajczaka Franciszka 90', 'Szczecin', 'Polska', '61-816');
INSERT INTO address(id, street, city, state, zip) VALUES(null, 'ul.Projektowa 142', 'Katowice', 'Polska', '91-493');
INSERT INTO address(id, street, city, state, zip) VALUES(null, 'ul.Tymiankowa 57', 'Lublin', 'Polska', '20-221');
INSERT INTO address(id, street, city, state, zip) VALUES(null, 'ul.Zgierska 27', 'Łódź', 'Polska', '91-468');
INSERT INTO student(id, name, surname, age, address_id) VALUES (null,'Adam', 'Nowak', 18, 1);
INSERT INTO student(id, name, surname, age, address_id) VALUES (null,'Bartosz', 'Pawlak', 20, 2);
INSERT INTO student(id, name, surname, age, address_id) VALUES (null,'Kinga', 'Kowalczyk', 21, 3);
INSERT INTO student(id, name, surname, age, address_id) VALUES (null,'Wiktor', 'Kowalski', 20, 4);
INSERT INTO student(id, name, surname, age, address_id) VALUES (null,'Piotr', 'Szczepański', 22, 5);
INSERT INTO student(id, name, surname, age, address_id) VALUES (null,'Filip', 'Chmielewski', 19, 6);